# Generated by Django 3.2 on 2021-04-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210412_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('place', models.CharField(max_length=200, verbose_name='Places')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
