# Generated by Django 3.2 on 2021-04-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_place_animal_latinn'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='typee',
            field=models.ManyToManyField(help_text='select an animal type', to='app.Type'),
        ),
    ]
