# Generated by Django 3.2 on 2021-04-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_animal_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='typee',
            field=models.ManyToManyField(help_text='select an animal type', to='app.Type', verbose_name='Type'),
        ),
    ]
