# Generated by Django 3.2 on 2021-04-12 12:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.poster_path, verbose_name='Image'),
        ),
    ]
